# Copyright (c) 2026 Hygon Information Technology Co., Ltd.
# SPDX-License-Identifier: MIT
# Modified by Hygon Information Technology Co., Ltd., 2026.

add_subdirectory(TritonGPUToLLVM)
add_subdirectory(TritonToTritonGPU)
add_subdirectory(TritonDistributedToLLVM)
add_subdirectory(TritonDistributedToTritonGPU)
